spring:
  application:
    name: project
  #profiles:
    #active: @activatedProperties@    # overridden by CI/Docker
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/project}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update #validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
      indent-output: true
    default-property-inclusion: non_null
  mail:
    properties:
      mail:
        smtp:
          ssl:
            trust: smtp.gmail.com
          starttls:
            required: 'true'
            enable: 'true'
          auth: 'true'
    username: ${MAIL_USERNAME:user}
    host: smtp.gmail.com
    port: '587'
    password: ${MAIL_PASSWORD:pass}

  # === Keycloak Resource Server config ===
  security:
    oauth2:
      resourceserver:
        jwt:
          # no /auth prefix for Keycloak 17+ (v24)
          issuer-uri: ${KEYCLOAK_AUTH_URL:http://localhost:8081}/realms/${KEYCLOAK_REALM:your-realm}

logging:
  level:
    root: INFO
    com.yourcompany: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.keycloak: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env
  endpoint:
    health:
      show-details: always

# Swagger/OpenAPI toggle
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

app:
  cors:
    allowed-origins: "http://localhost:4200"      # ← custom property
    allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
    allowed-headers: "Authorization,Content-Type,X-Requested-With"
